#  Met le level du logger a DEBUG et lui associe des appenders
log4j.logger.rcc_gui=debug, console, socket1, socket2

# l'appender console sert a afficher sur la console
log4j.appender.console=org.apache.log4j.ConsoleAppender

# console utilise PatternLayout pour la mise en forme 
# %r: nombre de milliseconde écouler depuis le début du programme
# %t: id du thread
# %-5p: niveau d'erreur (aligner à gauche)
# %c: nom du logger
# %m: message
log4j.appender.console.layout=org.apache.log4j.PatternLayout 
log4j.appender.console.layout.ConversionPattern=%d{(HH:mm:ss - dd/MM/yyyy)} %p - %m%n

#appender socket for Chainsaw
log4j.appender.socket1=org.apache.log4j.net.SocketAppender
log4j.appender.socket1.RemoteHost=localhost
log4j.appender.socket1.locationInfo=true
log4j.appender.socket1.Port=4445

#appender socket for RC GUI
log4j.appender.socket2=org.apache.log4j.net.SocketAppender
log4j.appender.socket2.RemoteHost=localhost
log4j.appender.socket2.Port=4000
log4j.appender.socket2.locationInfo=true
