
package rcc.rcc;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.7.16 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "rcc", targetNamespace = "urn:rcc/rcc.wsdl", wsdlLocation = "rcc.wsdl")
public class Rcc
    extends Service
{

    private final static Logger logger = Logger.getLogger(rcc.rcc.Rcc.class.getName());

    public Rcc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Rcc() {
        super(null, new QName("urn:rcc/rcc.wsdl", "rcc"));
    }

    /**
     * 
     * @return
     *     returns RccPortType
     */
    @WebEndpoint(name = "rcc")
    public RccPortType getRcc() {
        return super.getPort(new QName("urn:rcc/rcc.wsdl", "rcc"), RccPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RccPortType
     */
    @WebEndpoint(name = "rcc")
    public RccPortType getRcc(WebServiceFeature... features) {
        return super.getPort(new QName("urn:rcc/rcc.wsdl", "rcc"), RccPortType.class, features);
    }

}
