Menu.fore=139  0  139
Menu.back=255 255 255
Menu.font=DejaVu Serif Condensed-14
MenuItem.font=DejaVu Serif Condensed-14

Button.fore=178  34  34
Button.font=DejaVu Serif Condensed-16

Label.fore=20 20 20
Label.back= 64  64  64
Label.font=KacstTitle-16


ToolTip.fore=165  42  42
ToolTip.back= 16  16  16
ToolTip.font=Purisa-10
